### ISSUE TITLE
design reference

### ISSUE THREAD

**Issue by mathisonian** [jonuy/firearms-and-deaths#9]
hey @jonuy,

i came across this project on twitter - nice work on it. 

given the similarity of the simulator in your project and [this one](http://projects.fivethirtyeight.com/parole-assessment-simulator/) that i worked on for fivethirtyeight (published here: http://fivethirtyeight.com/features/prison-reform-risk-assessment/) it would be cool to provide a reference or link to that.

all the best,
matt

**Comment by jonuy** [comment]
@mathisonian _that's_ where I got it from! I was trying to remember where I saw it before but really couldn't remember. Thanks for your work on that. Yea, absolutely. I'll get to adding it in soon.

**Comment by mathisonian** [comment]
thanks @jonuy!

**Comment by jonuy** [comment]
Also note to self to add a design reference to the [Marshall Project](https://www.themarshallproject.org/next-to-die).
